language: python
python:
  - '3.4'
before_install:
  - pip3 install sqflint
script:
  - python3 herramientas/validation/sqf_validator.py
  - python3 herramientas/validation/config_style_checker.py
  - python3 herramientas/validation/sqf_linter.py
after_success:
    - nvm install lts/*
    - npx semantic-release
