jobs:
  include:
    - stage: test
      language: python
      python:
        - '3.4'
      install:
        - pip3 install sqflint
      script:
      - python3 herramientas/validation/sqf_validator.py
      - python3 herramientas/validation/config_style_checker.py
      - python3 herramientas/validation/sqf_linter.py
    - stage: release
      language: bash
      script:
      - nvm install lts/*
      - npm install @semantic-release/changelog -D
      - npm install @semantic-release/git -D
      - npx semantic-release
